// Build script to generate config.js from .env file
// Run this with: node build-config.js

const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '.env');
let supabaseUrl = '';
let supabaseAnonKey = '';

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');
    
    lines.forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
            const [key, ...valueParts] = trimmed.split('=');
            const value = valueParts.join('=').trim();
            
            if (key === 'SUPABASE_URL') {
                supabaseUrl = value;
            } else if (key === 'SUPABASE_ANON_KEY') {
                supabaseAnonKey = value;
            }
        }
    });
}

// Generate config.js
const configContent = `// Supabase Configuration
// This file is auto-generated from .env
// Do not edit this file directly - edit .env instead

const supabaseUrl = '${supabaseUrl}';
const supabaseAnonKey = '${supabaseAnonKey}';
`;

// Write config.js
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ config.js generated successfully from .env');
if (!supabaseUrl || !supabaseAnonKey) {
    console.log('⚠ Warning: Supabase credentials are empty. Make sure your .env file is configured.');
}


